### ISSUE TITLE
When registering new company account there should not be suggestions

### ISSUE THREAD

**Issue by FivelFred** [justarrived/just-match-frontend#501]
The user should enter its corporate number and click next. If availible since before it should load the data, otherwise not. It should be a list of options as now. Feels to exposing. 

![suggestion](https://cloud.githubusercontent.com/assets/16607246/15578446/c1840f9e-2360-11e6-9d93-b1b09c069846.PNG)

**Comment by buren** [comment]
I agree. My suggestion would be that the user enters the organisation number as usual, without feedback, and if there already is a company with that organisation number the user gets "redirected" to the next page.

**Comment by FivelFred** [comment]
I would really appreciate to have this fixed asap. This creates a lot of confusion for the company users.

**Comment by ti-sedp** [comment]
Fixed

Add Cancel button for back to input new organisation number and recheck organisation number in api again

**Comment by buren** [comment]
@ti-sedp fixed and merged? If so please close this issue, so we don't spend more time on this issue. :)

**Comment by FivelFred** [comment]
@ti-sedp the application does not load in the existing information of a company. could you look into this?

**Comment by buren** [comment]
@FivelFred I've deployed the latest version to production.

**Comment by FivelFred** [comment]
It still does not load the company information. And if there is no corporate information since before, it does give the alternative to add either. Please fix asap @ti-sedp @chris-sedp as none of our corporate users can register a new account currently.

**Comment by ti-sedp** [comment]
Now i get company information when click continue button. If api return company information I'll register that user with this company. If api not return company information It'll ask you add new company information. You can try this by register with the old user that already have in the system

![2559-06-14_17h45_38](https://cloud.githubusercontent.com/assets/16758634/16040103/e6105312-3257-11e6-9ed3-c9bc6fab40bb.png)

after submit with the error user information you'll see this

![2559-06-14_17h45_54](https://cloud.githubusercontent.com/assets/16758634/16040116/f9f3a690-3257-11e6-98ac-1d0c44dfe324.png)

Or which step you want to get company information ?

**Comment by FivelFred** [comment]
If you tab out of the Corporate Identification Number or click in another field that should trigger the front-end to retrieve the information. If there is no information the user should be able to enter corporate details straight away. Am I making myself clear?

**Comment by ti-sedp** [comment]
Fixed get company information after user tab out from the text field

**Comment by FivelFred** [comment]
@buren can we push to production?
